name: C++ CI (02-addressing)

on:
  push:
    paths:
      - 'lib/NetworkUtils.*'
      - 'projects/02-addressing/**'
      
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libpcap-dev flex bison
      - name: Build project (parallel)
        run: |
          cmake -S . -B build
          cmake --build build --parallel $(nproc) --target 02-addressing 02-addressing-tests
      - name: Run doctest tests with CTest
        run: |
          cd build
          ctest --output-on-failure -R "02-addressing"
