name: C++ CI (03-udp)

on:
  push:
    paths:
      - 'projects/03-udp/**'

jobs:
  udp-03:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ flex bison
      - name: Build project (parallel)
        run: |
          cmake -S . -B build
          cmake --build build --parallel $(nproc) --target 03-udp-tests
      - name: Run doctest tests with CTest
        run: |
          cd build
          ctest --output-on-failure -R "03-udp-tests"
